### ISSUE TITLE
Broadwell Core i3-5010U, kernel_task high CPU

### ISSUE THREAD

**Issue by probonopd** [Piker-Alpha/ssdtPRGen.sh#282] opened 2016-10-08 17:33 UTC
`kernel_task` has high CPU usage, what can I do?

```
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

Brandstring: "Intel(R) Core(TM) i3-5010U CPU @ 2.10GHz"
```

**Comment by Piker-Alpha** [comment] 2016-10-10 07:21
That is not something that I can help you with, but the i3 processors are not the quicker and thus  something like spotlight for example can take a long time to complete. Anyway. Since this is not something caused by the script, and It can be anything, I am about to close this issue as invalid.

**Closed as completed by Piker-Alpha** 2016-10-10 07:21 UTC
Labels: invalid
